name: yaltai
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=3_kmp_llvm
  - adwaita-icon-theme=48.0=h06a4308_0
  - alsa-lib=1.2.14=h5eee18b_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - asttokens=3.0.0=py311h06a4308_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - aws-c-auth=0.7.31=he1a10d6_2
  - aws-c-cal=0.7.4=hae4d56a_2
  - aws-c-common=0.9.29=hb9d3cd8_0
  - aws-c-compression=0.2.19=h2bff981_2
  - aws-c-event-stream=0.4.3=h19b0707_4
  - aws-c-http=0.8.10=h14a7884_2
  - aws-c-io=0.14.19=hc9e6898_1
  - aws-c-mqtt=0.10.7=hb8d5873_2
  - aws-c-s3=0.6.7=h666547d_0
  - aws-c-sdkutils=0.1.19=h2bff981_4
  - aws-checksums=0.1.20=h2bff981_1
  - aws-crt-cpp=0.28.3=hbe26082_8
  - aws-sdk-cpp=1.11.407=h25d6d5c_1
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.8.0=hd126650_2
  - azure-storage-blobs-cpp=12.12.0=hd2e3451_0
  - azure-storage-common-cpp=12.7.0=h10ac4d7_1
  - azure-storage-files-datalake-cpp=12.11.0=h325d260_1
  - blas=1.0=openblas
  - brotli-python=1.1.0=py311hfdbb021_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - cffi=2.0.0=py311h5b438cf_0
  - cfitsio=4.5.0=h44b4e7a_0
  - comm=0.2.3=py311h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.16=py311hbdd6827_1
  - decorator=5.2.1=py311h06a4308_0
  - double-conversion=3.3.1=h5888daf_0
  - epoxy=1.5.10=h166bdaf_1
  - executing=2.2.1=py311h06a4308_0
  - ffmpeg=6.1.2=gpl_h8657690_705
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - freeglut=3.4.0=h8b03031_1
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h7b6447c_0
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - geos=3.11.1=h27087fc_0
  - gflags=2.2.2=h6a678d5_1
  - ghostscript=10.04.0=h5888daf_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6287aef_0
  - glib-tools=2.84.2=h4833e2c_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h92a432a_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=12.2.1=h5ae0cbf_1
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=11.2.1=h3beb420_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hicolor-icon-theme=0.17=h06a4308_2
  - icu=75.1=he02047a_0
  - imageio=2.37.0=py311h06a4308_0
  - imagemagick=7.1.1_44=gpl_h069d9b9_0
  - imath=3.1.12=h7955e40_0
  - importlib-resources=6.4.0=pyhd3eb1b0_0
  - importlib_resources=6.4.0=py311h06a4308_0
  - ipykernel=6.31.0=py311h7040dfc_0
  - ipython=9.7.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - jasper=4.2.5=h1920b20_0
  - jbig=2.1=hdba287a_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_1
  - jupyter_core=5.8.1=py311h06a4308_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py311h06a4308_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.3=h6a678d5_0
  - libarchive=3.7.7=hadbb8c3_0
  - libarrow=17.0.0=had3b6fe_16_cpu
  - libarrow-acero=17.0.0=h5888daf_16_cpu
  - libarrow-dataset=17.0.0=h5888daf_16_cpu
  - libarrow-substrait=17.0.0=hf54134d_16_cpu
  - libasprintf=0.24.1=h8e693c7_0
  - libass=0.17.3=h52826cd_2
  - libavif16=1.1.1=h104a339_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=6_ha36c22a_netlib
  - libclang-cpp20.1=20.1.7=default_h1df26ce_0
  - libclang13=20.1.7=default_he06ed0a_0
  - libcrc32c=1.1.2=h6a678d5_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.24=h86f0d12_0
  - libdicom=1.0.5=hd590300_1
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexif=0.6.21=h7f98852_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.24.1=h5888daf_0
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h3618099_0
  - libglu=9.0.3=h60c0c69_1
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgoogle-cloud=2.29.0=h435de7b_0
  - libgoogle-cloud-storage=2.29.0=h0121fbd_0
  - libgrpc=1.62.2=h15f2491_0
  - libheif=1.19.6=gpl_hc18d805_100
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libhwy=1.1.0=h00ab1b0_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=6_ha36c22a_netlib
  - liblapacke=3.9.0=6_ha36c22a_netlib
  - libllvm20=20.1.7=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmatio=1.5.28=hbb92ff5_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.6=h7f8727e_0
  - libopenblas=0.3.29=ha39b09d_0
  - libopencv=4.10.0=qt6_py311h84d94a4_606
  - libopenvino=2024.4.0=hac27bb2_0
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_0
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_0
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_0
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_0
  - libopenvino-onnx-frontend=2024.4.0=h56242b0_0
  - libopenvino-paddle-frontend=2024.4.0=h56242b0_0
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_0
  - libopenvino-tensorflow-frontend=2024.4.0=h358ae18_0
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_0
  - libopus=1.3.1=h5eee18b_1
  - libparquet=17.0.0=h39682fd_16_cpu
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2024.02.01=h2f2cdcf_0
  - librsvg=2.58.4=he92a37e_3
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.50.1=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libthrift=0.20.0=h0e7cc3e_1
  - libtiff=4.7.0=hf01ce69_5
  - libtorch=2.1.2=cpu_mkl_hff68eba_104
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libva=2.22.0=h4f16b4b_2
  - libvips=8.16.0=h6c8daf4_7
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.11.9=py311h06a4308_0
  - llvm-openmp=20.1.7=h024ca30_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib-inline=0.2.1=py311h06a4308_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - mysql-common=9.3.0=h266115a_0
  - mysql-libs=9.3.0=he0572af_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.5=py311h06a4308_0
  - nspr=4.36=h5888daf_0
  - nss=3.112=h159eef7_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openblas=0.3.1=hd130d23_0
  - opencv=4.10.0=qt6_py311hc414901_606
  - openexr=3.2.2=h04e0de5_2
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openslide=4.0.0=h58ba908_1
  - openssl=3.5.0=h7b32b05_1
  - orc=2.0.2=h669347b_0
  - packaging=24.2=py311h06a4308_0
  - pango=1.56.3=h9ac818e_1
  - parso=0.8.5=py311h06a4308_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=0_h5eee18b_perl5
  - pexpect=4.9.0=py311h06a4308_1
  - pillow=11.2.1=py311h1322bbf_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pkg-config=0.29.2=h1bed415_8
  - pkgconfig=1.5.4=py311h06a4308_0
  - platformdirs=4.3.7=py311h06a4308_0
  - pooch=1.8.2=py311h06a4308_0
  - poppler=24.12.0=hd7b24de_2
  - poppler-data=0.4.11=h06a4308_1
  - prompt-toolkit=3.0.52=py311h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.3=py311h06a4308_0
  - py-opencv=4.10.0=qt6_py311h074fb97_606
  - pyarrow=17.0.0=py311hbd00459_2
  - pyarrow-core=17.0.0=py311h4854187_2_cpu
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py311h06a4308_0
  - pydantic-core=2.27.1=py311h4aa5aa6_0
  - pygments=2.19.1=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python_abi=3.11=7_cp311
  - pytorch-lightning=2.5.0.post0=py311h06a4308_0
  - pyvips=2.2.3=py311h2664de4_1
  - pywavelets=1.8.0=py311h5eee18b_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - pyzmq=27.1.0=py311hcf8288c_1
  - qt6-main=6.8.3=h75f3359_3
  - rav1e=0.6.6=he8a937b_2
  - re2=2024.02.01=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - regex=2024.11.6=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - rich=13.9.4=py311h06a4308_0
  - rpds-py=0.22.3=py311h4aa5aa6_0
  - s2n=1.5.5=h3931f03_0
  - setuptools=69.5.1=py311h06a4308_0
  - simsimd=6.4.9=py311h9ecbd09_0
  - six=1.17.0=py311h06a4308_0
  - sleef=3.8=h1b44611_0
  - snappy=1.2.1=h6a678d5_0
  - stack_data=0.6.3=py311h06a4308_0
  - stringzilla=3.12.5=py311h9ecbd09_0
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.13.3=py311h06a4308_1
  - tbb=2021.13.0=hceb3a55_1
  - tifffile=2025.2.18=py311h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.1=py311h5eee18b_0
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=py311h06a4308_0
  - typing-extensions=4.12.2=py311h06a4308_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - urllib3=2.3.0=py311h06a4308_0
  - wayland=1.23.1=h3e06ad9_1
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=py311h06a4308_0
  - wheel=0.45.1=py311h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxinerama=1.1.5=h50385e7_1
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxt=1.3.1=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - attrs==25.3.0
      - cattrs==25.1.1
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - contourpy==1.3.2
      - coremltools==8.3.0
      - cycler==0.12.1
      - fast-deskew==1.0
      - filelock==3.18.0
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - idna==3.10
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - kraken==5.3.0
      - lightning==2.4.0
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mean-average-precision==2021.4.26.0
      - multidict==6.4.4
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.3.0
      - propcache==0.3.2
      - protobuf==3.20.3
      - py-cpuinfo==9.0.0
      - pyaml==25.7.0
      - pyparsing==3.2.3
      - python-bidi==0.6.6
      - pytz==2025.2
      - referencing==0.36.2
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.13.1
      - shapely==2.0.7
      - simple-slurm==0.3.6
      - tabulate==0.8.10
      - threadpoolctl==3.5.0
      - torch==2.4.0
      - torchvision==0.19.0
      - triton==3.0.0
      - tzdata==2025.2
      - ultralytics==8.3.155
      - ultralytics-thop==2.0.14
      - yaltai==2.0.5
      - yarl==1.20.1
